package com.siga.web;

import com.siga.security.SigaSecurity;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.security.core.Authentication;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.web.bind.annotation.*;import org.springframework.transaction.annotation.Transactional;
import java.util.*;

@Controller @RequestMapping("/admin") @PreAuthorize("hasRole('ADMINISTRADOR')")
public class AdminController {
 private final JdbcTemplate jdbc; private final PasswordEncoder encoder;
 public AdminController(JdbcTemplate jdbc,PasswordEncoder encoder){this.jdbc=jdbc;this.encoder=encoder;}
 @GetMapping("/usuarios") public String usuarios(Model m){m.addAttribute("userRows",jdbc.queryForList("SELECT u.*,r.nombre rol,c.nombre cliente FROM usuarios u JOIN roles r ON r.id=u.rol_id LEFT JOIN clientes c ON c.id=u.cliente_id ORDER BY u.id DESC"));m.addAttribute("roles",jdbc.queryForList("SELECT * FROM roles ORDER BY id"));m.addAttribute("clientes",jdbc.queryForList("SELECT * FROM clientes ORDER BY nombre"));return "admin/usuarios";}
 @PostMapping("/usuarios/save") public String saveUser(@RequestParam Map<String,String> f){Long id=f.get("id")==null||f.get("id").isBlank()?0:Long.valueOf(f.get("id"));if(id==0){jdbc.update("INSERT INTO usuarios(nombre_completo,documento,email,telefono,password_hash,rol_id,activo,cliente_id) VALUES(?,?,?,?,?,?,?,?)",f.get("nombre_completo"),f.get("documento"),f.get("email"),f.get("telefono"),encoder.encode(f.getOrDefault("password","Admin123!")),Long.valueOf(f.get("rol_id")),"1".equals(f.get("activo")),Long.valueOf(f.get("cliente_id")));}else{jdbc.update("UPDATE usuarios SET nombre_completo=?,documento=?,email=?,telefono=?,rol_id=?,activo=?,cliente_id=? WHERE id=?",f.get("nombre_completo"),f.get("documento"),f.get("email"),f.get("telefono"),Long.valueOf(f.get("rol_id")),"1".equals(f.get("activo")),Long.valueOf(f.get("cliente_id")),id);if(f.getOrDefault("password","").length()>=6)jdbc.update("UPDATE usuarios SET password_hash=? WHERE id=?",encoder.encode(f.get("password")),id);}return "redirect:/admin/usuarios";}
 @GetMapping("/usuarios/{id}/edit") public String editUser(@PathVariable long id,Model m){m.addAttribute("editUser",jdbc.queryForMap("SELECT * FROM usuarios WHERE id=?",id));m.addAttribute("userRows",jdbc.queryForList("SELECT u.*,r.nombre rol,c.nombre cliente FROM usuarios u JOIN roles r ON r.id=u.rol_id LEFT JOIN clientes c ON c.id=u.cliente_id ORDER BY u.id DESC"));m.addAttribute("roles",jdbc.queryForList("SELECT * FROM roles ORDER BY id"));m.addAttribute("clientes",jdbc.queryForList("SELECT * FROM clientes ORDER BY nombre"));return "admin/usuarios";}
 @PostMapping("/usuarios/{id}/delete") public String delUser(@PathVariable long id){jdbc.update("DELETE FROM usuarios WHERE id=?",id);return "redirect:/admin/usuarios";}
 @GetMapping("/clientes") public String clientes(Model m){m.addAttribute("clients",jdbc.queryForList("SELECT * FROM clientes ORDER BY id DESC"));return "admin/clientes";}
 @PostMapping("/clientes/save") public String saveClient(@RequestParam Map<String,String> f){Long id=f.get("id")==null||f.get("id").isBlank()?0:Long.valueOf(f.get("id"));if(id==0)jdbc.update("INSERT INTO clientes(nombre,nit,telefono,email,direccion,activo) VALUES(?,?,?,?,?,?)",f.get("nombre"),f.get("nit"),f.get("telefono"),f.get("email"),f.get("direccion"),"1".equals(f.get("activo")));else jdbc.update("UPDATE clientes SET nombre=?,nit=?,telefono=?,email=?,direccion=?,activo=? WHERE id=?",f.get("nombre"),f.get("nit"),f.get("telefono"),f.get("email"),f.get("direccion"),"1".equals(f.get("activo")),id);return "redirect:/admin/clientes";}
 @GetMapping("/clientes/{id}/edit") public String editClient(@PathVariable long id,Model m){m.addAttribute("editClient",jdbc.queryForMap("SELECT * FROM clientes WHERE id=?",id));m.addAttribute("clients",jdbc.queryForList("SELECT * FROM clientes ORDER BY id DESC"));return "admin/clientes";}
 @PostMapping("/clientes/{id}/delete") public String delClient(@PathVariable long id){jdbc.update("DELETE FROM clientes WHERE id=?",id);return "redirect:/admin/clientes";}
 @GetMapping("/roles") public String roles(Model m){var roles=jdbc.queryForList("SELECT * FROM roles ORDER BY id");m.addAttribute("roles",roles);m.addAttribute("permisos",jdbc.queryForList("SELECT * FROM permisos ORDER BY nombre"));Map<Long,Set<Long>> rp=new HashMap<>();for(var r:roles){Long rid=((Number)r.get("id")).longValue();rp.put(rid,new HashSet<>(jdbc.queryForList("SELECT permiso_id FROM rol_permisos WHERE rol_id=?",Long.class,rid)));}m.addAttribute("rolePerms",rp);return "admin/roles";}
 @PostMapping("/roles/save") public String saveRole(@RequestParam Map<String,String> f){Long id=f.get("id")==null||f.get("id").isBlank()?0:Long.valueOf(f.get("id"));if(id==0)jdbc.update("INSERT INTO roles(nombre,descripcion) VALUES(?,?)",f.get("nombre"),f.get("descripcion"));else jdbc.update("UPDATE roles SET nombre=?,descripcion=? WHERE id=?",f.get("nombre"),f.get("descripcion"),id);return "redirect:/admin/roles";}
 @PostMapping("/roles/{id}/permisos") @Transactional public String savePermisos(@PathVariable long id,@RequestParam(required=false) List<Long> permisoIds){jdbc.update("DELETE FROM rol_permisos WHERE rol_id=?",id);if(permisoIds!=null)for(Long p:permisoIds)jdbc.update("INSERT INTO rol_permisos(rol_id,permiso_id) VALUES(?,?)",id,p);return "redirect:/admin/roles";}
}
